server:
  port: 8001

spring:
  application:
    name: cloud-payment-service-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://47.100.20.166:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: lsh
    password: Lsh123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.lyzd.cloud.pojo    # 所有Entity别名类所在包

eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://eureka7002.com:7002/eureka